### ISSUE TITLE
In ffprobe command timeot=${timeoutInSec} is not working

### ISSUE THREAD

**Issue by zarej** [LCMApps/video-quality-tools#92]
In following line timeot=${timeoutInSec} https://github.com/LCMApps/video-quality-tools/blob/master/src/FramesMonitor.js#L278 is not working. It receives Error 404. When I remove timeot=${timeoutInSec} it starts to work.

**Comment by WoZ** [comment]
Thank you for the issue!

The reason is that `rtmp` supports `timeout` option while `http` doesn't. The fix will be ready soon!

http://ffmpeg.org/ffmpeg-protocols.html

**Comment by WoZ** [comment]
Fixed in #96 
We changed `timeoutInSec` to `timeoutInMs` and added support of timeout for non-librtmp builds. Check that pull request to find details.
