### ISSUE TITLE
Analyze video with GOP > 5 sec  

### ISSUE THREAD

**Issue by oleh-poberezhets** [LCMApps/video-quality-tools#97]
`StreamsInfo` and `FramesMonitor` detects the only audio stream if video GOP is more then 5 sec.
In FFmpeg v3.x it leads to process crash with error: `Program received signal SIGSEGV, Segmentation fault`.

**Comment by oleh-poberezhets** [comment]
FFmpeg has a special option for this case:

> analyzeduration integer (input)
Specify how many microseconds are analyzed to probe the input. A higher value will enable detecting more accurate information, but will increase latency. It defaults to 5,000,000 microseconds = 5 seconds.

https://www.ffmpeg.org/ffmpeg-all.html#Format-Options

**Comment by WoZ** [comment]
Good, let do it.
